theme: jekyll-theme-midnight
description: An interactive website covering the 5 Big Ideas of College Board AP Computer Science Principles. See the [website ideation](https://github.com/TheRadRabbidRabbit/Team-Lovelace/wiki/Website-Ideation#purpose) Wiki for more information.
email: "l1965921542@gmail.com"
layout: default
title: "Lovelace-website"
author: "Tianbin Liu"

